#leftshift operations
print("enter the number:")
a=int(input())
print("leftshift operations from 1 to 10")
print("leftshift1 ",a<<1)
print("leftshift2 ",a<<2)
print("leftshift3 ",a<<3)
print("leftshift4 ",a<<4)
print("leftshift5 ",a<<5)
print("leftshift6 ",a<<6)
print("leftshift7 ",a<<7)
print("leftshift8 ",a<<8)
print("leftshift9 ",a<<9)
print("leftshift10 ",a<<10)
